# Use Node.js version 12 as the base image
FROM node:12-alpine

# Set the working directory in the container
WORKDIR /app

# Install Python and build tools
RUN apk add --update --no-cache python2 g++ make

# Copy package.json and package-lock.json for installing dependencies
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Vue CLI serves on port 8080 by default, expose that port
EXPOSE 8080

# Command to run the app using npm
CMD ["npm", "run", "serve"]

# to run locally:
# docker build -f Dockerfile.dev -t yourapp .
# docker run -v $(pwd):/app -p 8080:8080 --rm yourapp